version: '3.1'
services:
  db:
    container_name: dev_mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Seoul